# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f7413166102c7fdbfe1cbf79bd27618ae55f995b7f36121c7eacbe9720cd8955d11a33dee79579af3f24a17c94c1bc6456d84e16e1b915f796a0f9b898aef83

test:
  secret_key_base: 7230303f41f48d1f2d1e5e39f80a8c817dc2b2eb366952c04793e40d705ab0afc598a3cb55a40a5f37a77fd98cabeaad9ad5aedc56569f8f82374767b30b16de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
